services:
  service:
    image: mikebrady/shairport-sync
    security_opt:
      - label=disable  # arggggg, needed for secret to work, why????
    # https://github.com/containers/podman/issues/20418
    # https://github.com/containers/podman/pull/20962
    # restart: unless-stopped
    restart: always
    network_mode: host
    command: -a Küche -- -d hw:1,0 -m hw:1 -c Master
    volumes:
      # https://docs.docker.com/engine/storage/bind-mounts/#configure-the-selinux-label
      - ./shairport-sync.conf:/etc/shairport-sync.conf:Z
      - ./switch_power:/usr/local/bin/switch_power:Z
    devices:
      - /dev/snd
    secrets:
      - ha_access_token
secrets:
  ha_access_token:
    file: ./ha_access_token
