#cloud-config
prefer_fqdn_over_hostname: false
hostname: ShairportSyncKueche
ssh_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAII76gjWeMy9xfu7EAD2guCp4QoP9UGQtPEbQgsFLjXSE
locale: de_DE.UTF-8
timezone: Europe/Berlin
runcmd:
  - echo 'options snd_hda_intel power_save=0' >> /etc/modprobe.d/snd_hda_intel.conf
  - echo 0 > /sys/module/snd_hda_intel/parameters/power_save
  - amixer -c 1 sset 'Headphone' unmute
  - amixer -c 1 sset 'Headphone' 100%
  - amixer -c 1 sset 'Speaker' 0%
  - amixer -c 1 sset 'Speaker' mute
  - amixer -c 1 sset 'Master' unmute
  - alsactl store
  - systemctl enable podman.socket
  - systemctl start podman.socket
  - systemctl enable podman-restart
  - systemctl start podman-restart
  - "COMPOSE_PATH=/usr/bin/docker-compose && curl --location 'https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64' --output $COMPOSE_PATH && chmod 755 $COMPOSE_PATH"
  - cd /home/*
  - git clone 'https://github.com/Alex1s/shairport-sync-docker-server.git'
  - chown -R 1000:1000 shairport-sync-docker-server
  - cd shairport-sync-docker-server && podman compose up -d && cd -
  - DEFAULT_USERNAME=$(basename /home/*)
  - mkdir /home/"$DEFAULT_USERNAME"/.bashrc.d
  - echo "alias podman='sudo podman'" >> /home/"$DEFAULT_USERNAME"/.bashrc.d/aliases
  - echo "alias pc='sudo podman compose'" >> /home/"$DEFAULT_USERNAME"/.bashrc.d/aliases
  - chown -R 1000:1000 /home/"$DEFAULT_USERNAME"/.bashrc.d
package_reboot_if_required: true
package_update: true
package_upgrade: true
packages:
  - qemu-guest-agent
  - podman
  - git-core
  - alsa-utils
  - langpacks-en
  - langpacks-de
